"""empty message

Revision ID: 4ddcd437fed7
Revises: bfc6f69ab9ee
Create Date: 2019-08-27 19:10:00.582400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ddcd437fed7'
down_revision = 'bfc6f69ab9ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('other_name', sa.String(length=30), nullable=True),
    sa.Column('father', sa.String(length=5), nullable=True),
    sa.Column('keyword', sa.String(length=100), nullable=True),
    sa.Column('info', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('info', sa.String(length=255), nullable=True),
    sa.Column('text', sa.String(length=20000), nullable=True),
    sa.Column('read_num', sa.Integer(), nullable=True),
    sa.Column('praise_num', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('ispublic', sa.Boolean(), nullable=True),
    sa.Column('categoryid', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['categoryid'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('info', sa.String(length=255), nullable=True),
    sa.Column('articleid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['articleid'], ['article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('comments')
    op.drop_table('article')
    op.drop_table('category')
    # ### end Alembic commands ###
