"""empty message

Revision ID: 76293c9264ef
Revises: b88599b438a4
Create Date: 2019-08-31 08:51:25.648271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76293c9264ef'
down_revision = 'b88599b438a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('toname', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'toname')
    # ### end Alembic commands ###
