"""empty message

Revision ID: a224bea1087f
Revises: 4ddcd437fed7
Create Date: 2019-08-30 08:41:52.066523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a224bea1087f'
down_revision = '4ddcd437fed7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('is_delete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'is_delete')
    # ### end Alembic commands ###
