"""empty message

Revision ID: ccff17983614
Revises: 236b41c054b0
Create Date: 2019-08-31 10:03:21.631132

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ccff17983614'
down_revision = '236b41c054b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'b')
    op.drop_column('comments', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('date', sa.DATE(), nullable=True))
    op.add_column('comments', sa.Column('b', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
