"""empty message

Revision ID: d01860e1b346
Revises: 76293c9264ef
Create Date: 2019-08-31 10:01:11.105666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd01860e1b346'
down_revision = '76293c9264ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('a', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'a')
    # ### end Alembic commands ###
